In [2]:
### Run first done mess with ####

import pytrends
from matplotlib import pyplot as plt

from datetime import datetime, timedelta, date, time
import pandas as pd
import time

In [3]:
df = pd.read_csv('maincsv.csv')
stockdf = pd.read_csv('complete_stock_data .csv')

In [7]:
mainDf = stockdf.merge(df, on="Date", how="left")

In [11]:
mainDf.to_csv('mainDf.csv')

In [12]:
temp = pd.read_csv('mainDf.csv')

,Unnamed: 0,Date,MRNA_Open,MRNA_Close,MRNA_Difference,MRNA_Volume,JNJ_Open,JNJ_Close,JNJ_Difference,JNJ_Volume,...,athlete,prediction,tumble,stroke,diabetes,lungs,ivermectin,hydroxychloroquine,bleach,lake
0,0,2019-12-02,20.30,19.76,0.54,1184000,137.72,137.36,0.36,4717100,...,41.0,7.0,81.0,57.0,72.0,44.0,1.0,0.0,15.0,34.0
1,1,2019-12-03,19.48,21.28,-1.80,1795200,136.91,137.16,-0.25,5741400,...,40.0,8.0,72.0,53.0,77.0,48.0,1.0,0.0,16.0,35.0
2,2,2019-12-04,21.00,21.27,-0.27,1980100,138.50,139.38,-0.88,7257300,...,42.0,9.0,69.0,61.0,77.0,49.0,1.0,0.0,15.0,35.0
3,3,2019-12-05,21.49,20.64,0.85,1478100,139.35,139.56,-0.21,5472900,...,42.0,8.0,70.0,56.0,71.0,45.0,1.0,0.0,15.0,36.0
4,4,2019-12-06,20.78,18.94,1.84,3537200,139.46,140.38,-0.92,6640400,...,31.0,9.0,74.0,47.0,61.0,34.0,1.0,0.0,18.0,37.0