In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from pathlib import Path

In [2]:
%matplotlib inline
plt.rcParams['figure.figsize'] = 10, 8
plt.style.use("seaborn")

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, classification_report
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, MinMaxScaler, LabelEncoder


from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.pipeline import make_pipeline
from sklearn.model_selection import cross_validate

In [3]:
bi_df = pd.read_csv('../Model Data/final_binary_stonks_model_data.csv')
print(bi_df.dtypes)
bi_df.head()

Unnamed: 0        int64
Binary_Class     object
Search Date      object
MRNA_Open       float64
MRNA_Close      float64
                 ...
gig economy     float64
stimmy          float64
trump           float64
biden           float64
china           float64
Length: 106, dtype: object

,Unnamed: 0,Binary_Class,Search Date,MRNA_Open,MRNA_Close,MRNA_Difference,MRNA_Volume,JNJ_Open,JNJ_Close,JNJ_Difference,...,what is ivermectin,what is mrna,bill gates population control,ubereats,instacart jobs,gig economy,stimmy,trump,biden,china
0,0,High,2022-02-13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,High,2022-02-12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,Low,2022-02-11,161.25,161.32,-0.07,5245700.0,169.12,167.71,1.41,...,18.0,44.0,0.0,55.0,18.0,4.0,0.0,2.0,4.0,26.0
3,3,Low,2022-02-10,158.00,160.42,-2.42,5965400.0,171.21,169.42,1.79,...,20.0,34.0,11.0,45.0,8.0,2.0,0.0,2.0,5.0,28.0
4,4,Low,2022-02-09,154.37,164.03,-9.66,5621600.0,172.07,171.49,0.58,...,21.0,44.0,5.0,33.0,17.0,3.0,0.0,2.0,7.0,27.0

In [4]:
bi_df = bi_df.drop(columns={'Unnamed: 0', 'Search Date'})
bi_df = bi_df.dropna()
bi_df.head()

,Binary_Class,MRNA_Open,MRNA_Close,MRNA_Difference,MRNA_Volume,JNJ_Open,JNJ_Close,JNJ_Difference,JNJ_Volume,BTNX_Open,...,what is ivermectin,what is mrna,bill gates population control,ubereats,instacart jobs,gig economy,stimmy,trump,biden,china
2,Low,161.25,161.32,-0.07,5245700.0,169.12,167.71,1.41,13124800.0,167.93,...,18.0,44.0,0.0,55.0,18.0,4.0,0.0,2.0,4.0,26.0
3,Low,158.00,160.42,-2.42,5965400.0,171.21,169.42,1.79,10355300.0,165.04,...,20.0,34.0,11.0,45.0,8.0,2.0,0.0,2.0,5.0,28.0
4,Low,154.37,164.03,-9.66,5621600.0,172.07,171.49,0.58,5387500.0,162.90,...,21.0,44.0,5.0,33.0,17.0,3.0,0.0,2.0,7.0,27.0
5,High,155.20,153.31,1.89,7616400.0,171.02,171.51,-0.49,6296100.0,162.35,...,6.0,38.0,0.0,43.0,30.0,3.0,0.0,2.0,3.0,34.0
6,High,162.20,160.27,1.93,4429300.0,171.41,171.06,0.35,6065700.0,175.59,...,9.0,36.0,11.0,47.0,26.0,7.0,1.0,2.0,2.0,33.0

In [5]:
bi_df.select_dtypes(exclude=[np.number])

    Binary_Class  DJIA_Open DJIA_Close DJIA_Difference  DJIA_Volume
2            Low  35,267.89  34,738.06          529.83  398,860,000
3            Low  35,630.81  35,241.59          389.22  411,620,000
4            Low  35,614.90  35,768.06         -153.16  333,610,000
5           High  35,160.68  35,462.78          -302.1  319,190,000
6           High  35,108.38  35,091.13           17.25  328,910,000
..           ...        ...        ...             ...          ...
747          Low  25,865.08  26,024.96         -159.88  351,780,000
749          Low  23,437.34  23,475.82          -38.48  352,880,000
750          Low  19,028.36  18,591.93          436.43  787,970,000
751          Low  29,146.53  28,992.41          154.12  311,210,000
752          Low  29,111.02  29,160.09          -49.07  307,060,000

[501 rows x 5 columns]

In [6]:
#change data types from str to numeric
bi_df['DJIA_Open'] = pd.to_numeric(bi_df['DJIA_Open'],
                                     errors = 'coerce')
bi_df['DJIA_Close'] = pd.to_numeric(bi_df['DJIA_Close'],
                                     errors = 'coerce')
bi_df['DJIA_Difference'] = pd.to_numeric(bi_df['DJIA_Difference'],
                                     errors = 'coerce')
bi_df['DJIA_Volume'] = pd.to_numeric(bi_df['DJIA_Volume'],
                                     errors = 'coerce')

In [7]:
bi_df.select_dtypes(exclude=[np.number])

    Binary_Class
2            Low
3            Low
4            Low
5           High
6           High
..           ...
747          Low
749          Low
750          Low
751          Low
752          Low

[501 rows x 1 columns]

In [8]:
X = bi_df.drop(columns=['Binary_Class'])
y = bi_df['Binary_Class']
target_names = ["High", "Low"]

In [9]:
y_label = LabelEncoder().fit_transform(y)
y_label

array([1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y_label, random_state=42)

In [11]:
scaler = StandardScaler().fit(X_train)
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/extmath.py:770: RuntimeWarning: invalid value encountered in true_divide
  updated_mean = (last_sum + new_sum) / updated_sample_count
/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/extmath.py:711: RuntimeWarning: Degrees of freedom <= 0 for slice.
  result = op(x, *args, **kwargs)

In [14]:
rfc = RandomForestClassifier(random_state=1, n_estimators=500).fit(X_train_scaled, y_train)
print(f'Training Score: {rfc.score(X_train_scaled, y_train)}')
print(f'Testing Score: {rfc.score(X_test_scaled, y_test)}')

ValueError: Input contains NaN, infinity or a value too large for dtype('float32').

In [ ]:
feature_importances = rfc.feature_importances_

In [ ]:
features = sorted(zip(X.columns, rfc.feature_importances_), key = lambda x: x[1])
cols = [f[0] for f in features]
width = [f[1] for f in features]

fig, ax = plt.subplots()

fig.set_size_inches(10,200)
plt.margins(y=0.001)

ax.barh(y=cols, width=width)

plt.show()

In [ ]:
feat_plot=pd.Series(rfc.feature_importances_, index=X_train.columns).nlargest(10).sort_values(ascending=False)[:200].plot(kind='bar', figsize=(10,10))
feat_plot